### ISSUE TITLE
Push Module

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#152]
# TODOs
- [x] Provide a mechanism to capture the device (push) token from `application:didRegisterForRemoteNotificationsWithDeviceToken:`
- [x] Provide a mechanism for removing the device token
- [x] Persist token to localStorage
- [x] Track events when token is first captured and when updated
- [x] Automatically determine if token is production or development version
