### ISSUE TITLE
Module Architecture Round 2

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#164]
# Problems we need to solve

- State changes should be thread safe
- There is no obvious/clean place to listen to application events and modify the app state
- Dependency management between stores is a nightmare
- Helper functions (getters, action creators) are confusing, module organization isn't consistent
- A lot of the functionality in the event manager needs to be reproduced in other modules and needs to be dry'd up
- There is no way for app code to be notified when asynchronous actions occur (e.g. how does an AppDelegate call the completion handler in the background fetch method?)

# TODOs

## Foundation

- [x] Change container from a protocol with default behaviour to an open class
- [x] Create operation base classes (async and grouped)
- [x] Create a thread safe operation queue to handle state changes on the container based on event module
- [x] Replace factories with reducers
- [x] Flatten the state tree so stores no longer have dependencies
- [x] Remove the concept of the service interface
- [x] Observe all application lifecycle events and provide an interface similar to NotificationCenter where modules can add blocks of functionality to each event
- [x] Add a "UIApplicationDidPulse" lifecycle event that runs on a timer with a configurable duration
- [x] Provide a way for operations to execute within a background task
- [x] Revisit the assembler approach
- [x] Container should no longer be a singleton
- [x] Remove data module
- [x] Deliver notifications through NotificationCenter when operations start/complete

## HTTP

- [x] Rename HTTPClientFactory to HTTPClientReducer
- [x] Make HTTPClientReducer conform to reducer and update tests
- [x] Create HTTPState and HTTPAssembler
- [x] Publicize all operations and actions
- [x] Import JSON and Identifier from Foundation

## Events

- [x] Extract state from EventManager class into an EventsState struct
- [x] Create EventsReducer
- [x] Remove EventManagerFactory and EventManagerService
- [x] Move public API functions (trackEvent, flushEvents) into operations
- [x] Move action and dispatcher extensions into operations
- [x] Update HTTP bridge to work with new HTTP module
- [x] Move periodic flush capability to container's "UIApplicationDidEnterBackground" and  "UIApplicationDidPulse" lifecycle block
- [x] Create an events assembler
- [x] Add the default set of context providers to assembler
- [x] Publicize all operations and actions
- [x] Remove container extensions

## Sync

- [x] Move sync functionality into an operation
- [x] Add an observer to container "UIApplicationDidBecomeActive" to automatically call sync when the app opens
- [x] Create an operation creator to expose sync function to app code
- [x] Remove SyncManager, SyncManagerFactory and SyncManagerService
- [x] Update HTTP bridge to work with new HTTP module
- [x] Publicize all operations and actions
- [x] Remove container extensions

## User (Identity)

- [x] Move identify, anonymize and update user to operations
- [x] Update HTTP bridge to work with new HTTP module
- [x] Remove UserService and UserFactory
- [x] Create UserStore
- [x] Publicize all operations and actions
- [x] Remove container extensions

## Rover

- [x] Update assemble function to automatically assemble default set of modules
- [x] Create operation creator functions for all operations developer should have access to
- [x] Create singleton assemble function

**Comment by seanrucker** [comment]
Done... all problems solved.
