### ISSUE TITLE
Final Dispatcher Cleanup

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#329]
## Todo
- [ ] Remove the `.dispatching` static instance of `OSLog`.
- [ ] Delete the entire Dispatcher folder from the Foundation module and since nothing else will be assembled in the FoundationAssembler, remove it as well.
- [ ] Delete the OpenURLAction – anywhere that was using it can just call `open(_:options:)` on `UIApplication.shared`.
