### ISSUE TITLE
Remove OpenNotificationAction

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#332]
To support #329 we need to remove this action.

## Todo

- [x] Inject an instance of `NotificationStore` into the `NotificationHandlerService`.
- [x] Move logic from the `OpenNotificationAction` class into the handle method of the `NotificationHandler`.
- [x] Delete the file.
- [x] Remove references in the `NotificationsAssembler`.
