### ISSUE TITLE
Remove PresentViewAction

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#333]
In order to support #329 we need to remove the `PresentViewAction`. The functionality within the action can be served as an extension to `UIApplication` since it has no state. 

## Todo

- [x] Move the functionality from within the action to a `UIApplication` extension. The file should exist in the RoverUI module under the extensions folder and be named `UI.UIApplication.swift`. The function signature should look the same as the corresponding one on `UIViewController`: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-present.
- [x] Replace all instances of `OSLog.dispatch` in the extension with `OSLog.general`.
- [x] Replace the single reference to `UIApplication.shared` with `self` since this is now an extension on `UIApplication`.
- [x] Delete the `PresentViewAction` class.
- [x] Remove the action registration from the `UIAssembler`.
