### ISSUE TITLE
Extract model out from Location module

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#338]
The repurposed RoverData module will now house a single .xcdatamodeld file and all the corresponding `NSManagedObject`s for beacons, geofences, notifications, events, campaigns and (possibly) experiences.

## Todo

- [x] Move the `Beacon` and `Geofence` models as well as the .xcdatamodeld file out of the RoverLocation module and into the RoverData module. The RoverData module can not have a dependency on CoreLocation so any reliance the models have will need to be rethought. The RoverLocation module can add extensions to the models defined in the RoverData module, just be sure to follow the convention: Place them in the Extensions folder and prefix the file name with "Location".
- [x] Move the `NSPersistentContainer` register calls from the `LocationAssembler` to the `DataAssembler`. Drop the `name` argument from the register signature and rename the model in the `NSPersistentContainer` constructor from "RoverLocation" to "Rover".
- [x] Move the two `NSManagedObjectContext` container register calls from the `LocationAssembler` to the `DataAssembler`. Rename them from `location.viewContext' and `location.backgroundContext` to `viewContext` and `backgroundContext`.
