### ISSUE TITLE
Mock EventQueue

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#339]
As a _temporary_ first step towards reworking the functionality provided by the EventQueue, create a mock class that no-ops the public API so the rest of our code can compile.

## Todo
- [ ] Wipe out all variables and methods from the EventQueue class other than `addEvent(_:)`, `flush()` and `addObserver(_:)`. No-op the implementations of these three methods.
- [ ] Remove the `containerDidAssemble(resolver:)` method from the `DataAssembler`.
- [ ] Delete the `Event.swift` and `EventsClient.swift` files.
- [ ] Move the remaining files `EventInfo.swift`, `EventQueueObserver.swift` and `EventQueue.swift` into the Foundation module under a subfolder named "Events" and update their target membership to the RoverFoundation module.

**Comment by seanrucker** [comment]
On second thought, don't need this.
