### ISSUE TITLE
Move Context from RoverData to RoverUI

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#341]
The word Context becomes confusing when we're using Core Data. We use the word Device elsewhere in our stack which makes it a reasonable replacement name. In addition, our model for capturing context, persisting some values and letting other modules contribute to the process is unnecessarily complicated. 

Also, most of the computed properties on the Context require UIKit so this class needs to be moved out of the RoverData module and into the RoverUI module.

## Todo
- [x] Rename the `Context` struct to `DeviceSnapshot` and _keep_ it in the RoverData module (put it in the root of the module for now).
- [x] Add a default value of `nil` to all initializer arguments so the `DeviceSnapshot` can be initialized without providing any arguments. I.e. `let snapshot = DeviceSnapshot()`.
- [x] Replace the following files with a single open class named `Device` which uses computed properties to return values. As an open class with computed properties, this allows easy developer customization with very little overhead. For the persisted values, use `UserDefaults` directly instead of the `PersistedValue` utility class. Save the `Device` class in the RoverUI module, not RoverData, and ensure the target membership is correct.
   - ContextManager
   - ContextProvider
   - ModularContextProvider
   - TokenManager
   - UserInfo
   - DebugContextProvider
   - LocaleContextProvider
   - NotificationsContextProvider
   - PushTokenContextProvider
   - ReachabilityContextProvider
   - StaticContextProvider
   - TimeZoneContextProvider
   - UserInfoContextProvider
- [x] For each of the 4 remaining ContextProviders, rename the protocols from "ContextProvider" to "InfoProvider".
   - AdSupportInfoProvider
   - BluetoothInfoProvider
   - LocationInfoProvider
   - TelephonyInfoProvider
- [x] The `Device` class should accept optional instances of the 4 info providers in its constructor and the `Device` class should delegate to these in its computed properties as it does today.
- [x] Add a computed variable named `snapshot` which builds and returns an instance of the `DeviceSnapshot` _struct_ from all the computed properties on the `Device` _class_.
- [x] Register the `Device` class in the `UIAssembler`.
- [x] Move the vendored `Reachabilty` class into RoverUI.
- [x] Delete the Context folder from RoverData.
- [x] Delete all context-related entries from the `DataAssembler`:
   - ContextManager
   - ContextProvider
   - LocaleContextProvider
   - PushTokenContextProvider
   - ReachabilityContextProvider
   - StaticContextProvider
   - TimeZoneContextProvider
   - TokenManager
   - UserInfoManager
   - UserInfoContextProvider

**Comment by orospakr** [comment]
I will assume that the field for the new DeviceSnapshot structure on EventSnapshot shall remain `deviceContext`.
