### ISSUE TITLE
EventPipeline Service

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#353]
The `EventPipeline` is responsible for creating/tracking events and notifying observers when events have been added. With a reference to the `NSManagedObjectContext` the `EventPipline` provides a simple API to add an event. It also wraps the `NSManagedObjectContextObjectsDidChange` API on the `NSManagedObjectContext` and provides a simple API to be notified when an event has been added.

## Todo

- [x] Create a public, open `EventPipeline` class. The initializer accepts an instance of `NSManagedObjectContext` as well as an instance of the `Device` class.
- [x] Register the `EventPipeline` class as a singleton in the DataAssembler. Resolved an instance of the `NSManagedObjectContext` named "background" to pass in the constructor.
- [x] Create an `addEvent(_:)` method which accepts an instance of `EventInfo`. The implementation should insert an `Event` object into the context, set the properties based on the values of the `EventInfo` and save the context. (The event.deviceSnapshot is calculated from the `Device` class injected through  the `EventPipeline` constructor. This should happen from within the `context.perform` block. 
- [x] In the event of an error in `addEvent(_:)` the context should be rolled back and the error logged. See the `insertObjects(from:)` method of the `PagingSyncParticipant` for how to check for and log multiple errors.
- [x] Add a public `ObserverSet` property to the `EventPipeline`: `var observers = ObserverSet<Event>()`.
- [x] Add a property to the `EventPipeline` class to reference an observer token: `var objectsDidChangeObserver: NSObject!`
- [x] In the initializer, where the `NSManagedObjectContext` is passed, add an observer: 
```
NotificationCenter.default.addObserver(forName: .NSManagedObjectContextObjectsDidChange, object: context, queue: nil) { [weak self] notification in
     
}
```
- [x] In the `deinit` remove the observer: `NotificationCenter.default.removeObserver(objectsDidChangeObserver)`.
- [x] In the implementation of the observer block, obtain the list of inserted objects from the `NSInsertedObjectsKey` key. Filter the set for `Event` objects since that's all we care about. If the set is not empty, notify the observers in the `ObserverSet`, one at a time for each updated event.

**Comment by orospakr** [comment]
Hmm, Device is in the UI module.  Data module clearly can't depend on the UI module.

Maybe we can indirect it somehow through a Protocol?
